### PR TITLE
[WIP] Overhauling the UI

### PR DESCRIPTION
**Pull request by PrincessAkira**
What i did:

- Added Boostrap
- Added Navbar
- Added content Boxes

Screenshot:
FYI Red Represents the Color to showcase that it autoscales
image

### CODE REVIEW

**Comment by PrincessAkira** [comment]
Showcase:


https://user-images.githubusercontent.com/45071533/224502531-046436c1-71a1-499b-9d9b-b95d55ae8a1a.mp4

**Comment by maxcutie** [comment]
that red is melting my eyes holy fuck

**Comment by PrincessAkira** [comment]
I mean its the easiest contrast to see if something is working

**Comment by PrincessAkira** [comment]
image
@hawolt i hope you saw this yet  XD

**Pull request merged**
